version: "v1.0.1"
rules:
  - name: "Thinkphp"
    matchers:
      - type: word
        part: header
        word:
          - "ThinkPHP"
  - name: "Apache"
    matchers:
      - type: regex
        part: header
        name: Apache
        regex:
          - "Server: .*?([aA]{1}pache[/]?[\\d\\.]*) ?"
        group: 1
  - name: "Nginx"
    matchers:
      - type: regex
        name: nginx
        part: header
        regex:
          - "Server: .*?([nN]{1}ginx[/]?[\\d\\.]*) ?"
        group: 1
  - name: "Halo"
    matchers:
      - type: regex
        name: halo
        part: body
        group: 1
        regex:
          - "content=\"(Halo .*?)\""
  - name: "PHP"
    matchers:
      - type: regex
        part: header
        name: php
        regex:
          - 'X-Powered-By: (PHP/?(\d+\.\d+\.\d+)?)'
        group: 1
  - name: "Tomcat"
    matchers:
      - type: regex
        name: tomcat
        part: body
        regex:
          - "([Tt]{1}omcat[/]?[\\d\\.]*)"
        group: 1
  - name: "AWS-EC2"
    matchers-condition: or
    matchers:
      - type: regex
        part: hedaer
        regex:
          - "Server: (EC2ws)"
      - type: word
        part: body
        words:
          - "Amazon EC2"
  - name: "Django"
    matchers:
      - type: word
        part: body
        words:
          - "<title>The install worked successfully! Congratulations!</title>"
          - "Django tried these URL patterns"
          - "Django will display a standard"
  - name: "Microsoft-IIS"
    matchers:
      - type: regex
        part: header
        name: iis
        group: 1
        regex:
          - "Server: .*?(Microsoft-IIS[/]?[\\d\\.]*)"
  - name: "Nacos"
    matchers:
      - type: word
        part: body
        words:
          - '<img class="product-logo" src="img/nacos.png">'
  - name: "WordPress"
    matchers:
      - type: regex
        part: body
        name: wordpress
        group: 1
        regex:
          - '<meta name="generator" content="(WordPress (\d+\.\d+\.\d+))"'
  - name: "Solr-Admin"
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        name: solr
        group: 1
        regex:
          - '<a href="#/~logging">Logging</a>'
      - type: word
        part: body
        words:
          - '<a href="#/" id="solr"><span>Apache SOLR</span></a>'
          - '<a href="#/~logging">Logging</a>'
          - '<a href="#/~cloud">Cloud</a>'
          - '<a href="#/~collections">Collections</a>'
        condition: and
  - name: "Phpinfo"
    matchers-condition: and
    matchers:
      - type: regex
        part: body
        name: phpinfo
        group: 1
        regex:
          - '<h1 class="p">PHP Version (\d+\.\d+\.\d+)</h1>'
      - type: word
        part: body
        words:
          - '<td class="e">System </td>'
          - '<td class="e">Server API </td>'
          - '<td class="e">disable_functions</td>'
        condition: or
  - name: "Splunk-Enterprise"
    matchers:
      - type: word
        part: body
        words:
          - '<p>Splunk relies on JavaScript to function properly.<br>Please enable JavaScript and then refresh the page to login.</p>'